name: Run Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        build-type: [Debug, Release]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2 # Clone repo

    - name: Generate build files 
      # The -DCMAKE_BUILD_TYPE variable only matters to single-config generators
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{ matrix.build-type }}

    - name: Build project
      # The --config option is only used on multi-config generators
      run: cmake --build ${{ github.workspace }}/build --config ${{ matrix.build-type }}

    - name: Run tests
      working-directory: ${{ github.workspace }}/build
      # Run the tests, selecting the configuration if possible.
      run: ctest -C ${{ matrix.build-type }} --output-on-failure
